### ISSUE TITLE
Adicionar validação dos campos de formulário

### ISSUE THREAD

**Issue by Silva-Cesar** [ICEI-PUC-Minas-PMV-ADS/pmv-sint-2024-1-e5-proj-mov-t1-time-quarta-19-00#21]
Validar campos de formulário de cadastro de usuário/instituição:
- Nome e nome de usuário não pode conter caracteres especiais nem números
- email deve conter um '@' e '.com'
- Validar se o CNPJ contém 14 dígitos numéricos

**Comment by VicenteRamon** [comment]
Foram adicionadas as validações de formulario
